### ISSUE TITLE
Dis7 Header PDU_status

### ISSUE THREAD

**Issue by adriano-tumino** [zlubsen/dis-rs#1]
When a **DIS 7** PDU is serialized without a **PDU Status**, the procedure is incorrect, and the resulting buffer/packet is malformed.
There is the need to add a default condition in `common\writer.rs`  (line 19):
```rs
if let Some(status) = self.pdu_status {
      status.serialize(buf);
      buf.put_u8(0u8);
} else {
      buf.put_u8(0u8); // Not coupled
      buf.put_u8(0u8); // Padding
}
```

**Comment by carlocorradini** [comment]
Same problem here 😬

**Comment by zlubsen** [comment]
Thank you for reporting the issue. I found an additional issue when the pdu_status was present as well... See v0.5.2 for the fix.
