### ISSUE TITLE
Signal pdu parsing fails with 16 bit audio data

### ISSUE THREAD

**Issue by znoble360** [zlubsen/dis-rs#13]
I've tried both this library and also the library here: https://github.com/crhowell3/open-dis-rust 
and the same issue seems to occur in both. When I try to parse a signal pdu that has a 16 bit encoding type for the audio data the library can't handle it and fails to parse it returning a parse error.

**Comment by zlubsen** [comment]
@znoble360 Do you have an example of the PDU you are trying to parse (hex blob, pcap file or something like that) and possibly a description of what you expect in the parsed struct? I'll take a look.

**Comment by znoble360** [comment]
I can work on getting you that

**Comment by znoble360** [comment]
So this should be 2 pdus, the first of which is a signal pdu with 16 bit pcm encoded audio, and the second one should be the exact same pdu with the only difference being the audio is instead encoded with 8 bit pcm.
[signal_pdus_16bit_and_8bit_pcm.pcap.tar.gz](https://github.com/zlubsen/dis-rs/files/14130787/signal_pdus_16bit_and_8bit_pcm.pcap.tar.gz)

**Comment by zlubsen** [comment]
Thanks, I'll review and add them as tests later.
For now, I found that the data length field in the Signal PDU is in bits, but it was used as bytes. I did a quick fix for this, you can try the 0.6.0-beta release uploaded to crates.io.
Be aware that this also includes some other changes, among which changed APIs for constructing PDUs. Instead of ```SomePdu::new()``` you should now use ```SomePdu::builder().with_x_y_z(some_value).build()```. Not yet consistent for all PDUs. And some re-exports changed because they were double.

**Comment by znoble360** [comment]
Ok terrific, thank you so much. I tested it and now it works just as expected

**Comment by znoble360** [comment]
Hmm, well I may have spoken too soon, I tried matching against/using some of the fields of the body and I'm getting compiler complaints about PduBody variants not being publicly re-exported, but I can't find the proper re-exports. Are you still in the middle of refactoring that, or am I just not seeing where it's re-exported?

**Comment by zlubsen** [comment]
No, looks like I was too rigorous in trimming down re-exports. Sorry about that. 0.6.0-beta-2 should be available... let me know if that works out. Any feedback on ergonomics and such is welcome as well.
