### ISSUE TITLE
pub trait BodyInfo

### ISSUE THREAD

**Issue by carlocorradini** [zlubsen/dis-rs#23]
Add `pub` to [`BodyInfo`](https://github.com/zlubsen/dis-rs/blob/92f4cc7a291075d88ddf335a597216ad2b208c7d/dis-rs/src/common/mod.rs#L84).

Functions in `BodyInfo` are very useful :)

**Comment by zlubsen** [comment]
Traits ``BodyInfo`` and ``Interaction`` are now public. Available on development and main branches, new release 0.8.0 published.

**Comment by carlocorradini** [comment]
Awesome 😎
