### ISSUE TITLE
Attempt to subtract with overflow

### ISSUE THREAD

**Issue by znoble360** [zlubsen/dis-rs#26]
I came to a situation where the parser seemed to consistently panic, but I wasn't able to figure out why or create it in different situations yet. The backtrace seems to point [here](https://github.com/zlubsen/dis-rs/blob/master/dis-rs/src/common/attribute/parser.rs#L51), and I added a simple block that checks if record_length_octets is less than BASE_ATTRIBUTE_RECORD_LENGTH_OCTETS before subtracting and that seems to prevent the panic. I'm not sure if there are other places where subtractions could possibly cause panics like this, but I think idealy this kind of thing would be caught/returned as an error instead of crashing. 

It should be parsing dis packets that are dis radio communication pdus, so I don't know why it's getting to the attribute parser, but I'm assuming I just had a malformed packet somehow somewhere. But malformed packets also I would think should just error instead of panicing.

**Comment by zlubsen** [comment]
Agreed, the library should not panic.
I'll have to go over situations where there are calculations going on to prevent over/underflows. These situations would typically mean that a PDU is malformed indeed, and the library should be robust for that.

**Comment by zlubsen** [comment]
Changed occurrences of subtractions in PDU parsers to use saturating_sub(). This works as these occurrences are used to take a number of bytes. Now the parser takes zero bytes when the count is wrong. Parsing will either succeed with malformed data, or fail with an EOF.
Merged to development branch.
