### ISSUE TITLE
Typo in autogenerated enumerations

### ISSUE THREAD

**Issue by carlocorradini** [zlubsen/dis-rs#39]
`dis_rs::enumerations::EntityKind::Lifeform` should be `dis_rs::enumerations::EntityKind::LifeForm`
`dis_rs::enumerations::EntityKind::Culturalfeature` should be `dis_rs::enumerations::EntityKind::CulturalFeature`

Both typos are caused by the fact that in SISO, they are two words separated by a space, with the second one in lowercase. 
I think more scenarios like this one need to be fixed **->** Fix the logic of how `build.rs` handles these names

**Comment by zlubsen** [comment]
The generator indeed 'just' takes the input from the SISO enumerations XML document. There is already (quite) some juggling with the input data to strip characters that cannot be in code etc. Adding a step to output proper camelcase enum names would be nice, mostly from a quality of life and naming convention point of view.

Option: use a crate like https://crates.io/crates/convert_case.

**Comment by zlubsen** [comment]
Fixed by PR #41, merged into development branch.
