### ISSUE TITLE
Code Formatting via rustfmt

### ISSUE THREAD

**Issue by carlocorradini** [zlubsen/dis-rs#40]
Enable code formatting via `rustfmt`

**Comment by zlubsen** [comment]
The code generated by build.rs is formatted using prettyplease, which I found to be nicer to integrate programmatically.

Is there a particular issue with the formatting?

**Comment by carlocorradini** [comment]
Ah nono easier :)
Format the whole project using rustfmt.
Example: build.rs is not formatted, integrate rustfmt :)

**Comment by carlocorradini** [comment]
Something way way easier

**Comment by zlubsen** [comment]
Applied rustfmt to whole project. To incorporate in any GitHub Actions pipeline later one.
