### ISSUE TITLE
EntityType FromStr .expect instead of unwrap_or

### ISSUE THREAD

**Issue by carlocorradini** [zlubsen/dis-rs#50]
https://github.com/zlubsen/dis-rs/blob/d3e209140132135eb1cc6dbe0218ab5295751ff7/dis-rs/src/common/model.rs#L925

The above should be changed to `.unwrap()` since we already check for the presence of 7 elements and therefore, if fore some reason, the element is `None`, we must **fail** since the assertion is not valid (and avoid unexpected results).

**Comment by zlubsen** [comment]
Fixed on development.

Replace with `.expect()` having a rationale for the panic.
